language: ruby
rvm:
  - 2.0.0
bundler_args: --without production
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec
notifications:
  email:
    recipients:
      - matias@munki.cl
